version: '3.8'

networks:
  traefik_net:
    external: true

services:
  nginx:
    image: nginx:latest
    networks:
      - traefik_net
    deploy:
      replicas: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nginx.rule=Host(`nginx.swarm.cloudns.ch`)"
        - "traefik.http.services.nginx.loadbalancer.server.port=80"
        - "traefik.http.routers.nginx.entrypoints=https"
        - "traefik.http.routers.nginx.tls=true"
        - "traefik.http.routers.nginx.tls.certresolver=myresolver"

