###############################################################
#                   Authelia configuration                    #
###############################################################
 
host: 0.0.0.0
port: 9091
log_level: warn

# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE
jwt_secret: 730178481E0194DC9E28E7EE987D7EAF5B59BB2D67D66463470EA65B527C24EC # use docker secret file instead AUTHELIA_JWT_SECRET_FILE

# https://docs.authelia.com/configuration/miscellaneous.html#default-redirection-url
default_redirection_url: https://authelia.traefik.swarm

totp:
  issuer: authelia.com
  period: 30
  skew: 1


authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 1024 # blocks this much of the RAM. Tune this.

      access_control:
  default_policy: deny
  rules:
    - domain: authelia.traefik.swarm
      policy: bypass
      
    - domain:
        - &amp;quot;*.traefik.swarm&amp;quot;
        - &amp;quot;traefik.swarm&amp;quot;
      policy: two_factor
session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  secret: ACE33E5E1A1C80A71042A4961D0A140EDA6371CB4055D2FC4496DA8C520D9312 # use docker secret file instead AUTHELIA_SESSION_SECRET_FILE
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: traefik.swarm # Should match whatever your root protected domain is

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

notifier:
  # For testing purposes, notifications can be sent in a file. Be sure to map the volume in docker-compose.
  filesystem:
    filename: /config/notification.txt

mysql:
  host: MYSQL_HOST
  port: 3306
  database: authelia
  username: autheliDB_user
  # Password can also be set using the env variables AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE
  password: toor # use docker secret file instead AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE